<?php

define('VR360_TOUR_STATUS_PENDING', 0);
define('VR360_TOUR_STATUS_PUBLISHED_READY', 1);
define('VR360_TOUR_STATUS_UNPUBLISHED', 2);

define('VR360_TOUR_DEFAULT_DEFAULTPANO', 0);
define('VR360_TOUR_SCENE_DEFAULT_FOV', 0);
define('VR360_TOUR_SCENE_DEFAULT_HLOOKAT', 0);
define('VR360_TOUR_SCENE_DEFAULT_VLOOKAT', 1.8);
