<?php

defined('_VR360_EXEC') or die;

define('VR360_TOUR_STATUS_PENDING', 0);
define('VR360_TOUR_STATUS_PUBLISHED_READY', 1);
define('VR360_TOUR_STATUS_UNPUBLISHED', 2);

define('VR360_TOUR_DEFAULT_PANO', 0);
define('VR360_TOUR_SCENE_DEFAULT_FOV', 179);
define('VR360_TOUR_SCENE_DEFAULT_HLOOKAT', 0);
define('VR360_TOUR_SCENE_DEFAULT_VLOOKAT', 1.8);

define('VR360_TOUR_SCENE_DEFAULT_FOVTYPE', 'MFOV');
define('VR360_TOUR_SCENE_DEFAULT_MAXPIXELZOOM', 2.0);
define('VR360_TOUR_SCENE_DEFAULT_FOVMIN', 70);
define('VR360_TOUR_SCENE_DEFAULT_FOVMAX', 140);
define('VR360_TOUR_SCENE_DEFAULT_LIMITVIEW', 'auto');

define('VR360_TOUR_TOUR_DEFAULT_AUTOROTATE_WAITTIME', 2.0);
define('VR360_TOUR_TOUR_DEFAULT_AUTOROTATE_SPEED', 2.0);
define('VR360_TOUR_TOUR_DEFAULT_AUTOROTATE_HORIZON', 0.0);

define('VR360_KRPANO_VIEWER_SWF_PATH', './krpano/viewer/krpano.swf');
define('VR360_KRPANO_VIEWER_JS_PATH', './krpano/viewer/krpano.js');
