<?php

defined('_VR360_EXEC') or die;

$parts = explode(DIRECTORY_SEPARATOR, VR360_PATH_BASE);

define('VR360_PATH_ROOT', VR360_PATH_BASE);
define('JPATH_ROOT', VR360_PATH_ROOT);

define('VR360_PATH_SITE', VR360_PATH_ROOT);
define('VR360_PATH_ADMINISTRATOR', VR360_PATH_ROOT . DIRECTORY_SEPARATOR . 'administrator');

define('VR360_PATH_LIBRARIES', VR360_PATH_ROOT . DIRECTORY_SEPARATOR . 'libraries');
define('VR360_PATH_VENDOR', VR360_PATH_ROOT . DIRECTORY_SEPARATOR . 'vendor');

define('VR360_PATH_DATA', VR360_PATH_ROOT . DIRECTORY_SEPARATOR . '_');
define('VR360_PATH_CACHE', VR360_PATH_ROOT . DIRECTORY_SEPARATOR . 'cache');
define('VR360_PATH_TMP', VR360_PATH_ROOT . DIRECTORY_SEPARATOR . 'tmp');

define('VR360_PATH_TEMPLATES', VR360_PATH_ROOT . DIRECTORY_SEPARATOR . 'templates');
define('VR360_PATH_ASSETS', VR360_PATH_ROOT . DIRECTORY_SEPARATOR . 'assets');
define('VR360_PATH_LAYOUTS', VR360_PATH_ROOT . DIRECTORY_SEPARATOR . 'layouts');

require_once VR360_PATH_ROOT . '/defines/environment.php';
require_once VR360_PATH_ROOT . '/defines/tour.php';